version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: musicclub-postgres
    restart: unless-stopped
    env_file: .env.db
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer: # опционально: веб-UI для БД
    image: adminer:4
    container_name: musicclub-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
